name: Check Minimum Score

on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

permissions:
  contents: read

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create model
        run:
          python train.py

      - name: Test model
        run: |
          OUTPUT=$(python test.py)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
  Train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t Assignment3 .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push Assignment3

      - name: Gracefully exit the job
        run: exit 0

  Test:
    runs-on: ubuntu-latest
    needs: Train
    steps:
      - name: Pull the Docker image from Docker Hub
        run: docker pull Assignment3

      - name: Run the fetched Docker image
        run: docker run Assignment3
